language: c

env:
    - SMVERSION=1.8

matrix:
    fast_finish: true
    
before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lynx
    - sudo apt-get install lib32stdc++6

before_script:
    - SMLATEST=`curl "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
    - SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp Anti_Private.sp addons/sourcemod/scripting/
    - cp include/smjansson.inc addons/sourcemod/scripting/include
    - cp include/SteamWorks.inc addons/sourcemod/scripting/include
    - cp include/steamtools.inc addons/sourcemod/scripting/include
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh
    
script: 
    - ./compile.sh Anti_Private.sp   
  
deploy:
  provider: releases
  api_key: "$githubkey"
  file: 
    - "$TRAVIS_BUILD_DIR/addons/sourcemod/scripting/compiled/Anti_Private.smx"
    - "$TRAVIS_BUILD_DIR/anti_private.phrases.txt"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false